SalCalc/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using SalCalc.Models;
using SalCalc.Models.Report;
using SalCalc.ViewModel;

namespace SalCalc.Controllers;

public class ReportController : Controller
{
    //Создания списка отчетов для каждого пользователя в отдельности
    private  static List<ReportList> _reportLists { get; set; }

    public ReportController()
    {
        _reportLists ??= new List<ReportList>();
    }
    private void SetGuid()
    {
        //Присваивание каждому пользователю уникального id и создания "отчета" для каждого пользователя и добавление в статистический список каждый раз когда пользователь открывает index, если отчет существует, пересоздает его
        var id = "";
        if (!HttpContext.Session.Keys.Contains("Guid"))
        {
            id = Guid.NewGuid().ToString();
            HttpContext.Session.SetString("Guid",id);
        }
        else
        {
            id = HttpContext.Session.GetString("Guid");
            var rep = _reportLists.FirstOrDefault(p => p.Id == id);
            if (rep != null)
                _reportLists.Remove(rep);
        }
        _reportLists.Add(new ReportList {Id = id});
    }

    private ReportList GetThisReport()
    {
        var id = HttpContext.Session.GetString("Guid");
        return  _reportLists.FirstOrDefault(p => p.Id == id);
    }
    public IActionResult Index()
    {
        HttpContext.Session.SetInt32("OpenPage", 3);
        SetGuid();
        ICommand command = new EmployeeCommand<Employee>();
        var userList = command.GetDataList<Employee>();
        return View(new ReportViewModel{ EmployeeList = userList});
    }

    public void AddUserInReport(int id, int year,int month, bool withMonth)
    {
        var rep = GetThisReport();
        ICalcSalary calcSalary;
        if (withMonth)
            calcSalary = new CalcSalaryWithMonth();
        else
            calcSalary = new CalcSalaryWithoutMonth();
        ICommand command = new EmployeeCommand<int>(id);
        var user = command.GetData<Employee>();
        rep.AddNewReport(user, year, month, calcSalary);
    }

    public IActionResult GetReport()
    {
        return View("ReportList", GetThisReport());
    }
}

SalCalc/Controllers/SalaryController.cs
using Microsoft.AspNetCore.Mvc;
using SalCalc.Models;
using SalCalc.ViewModel;

namespace SalCalc.Controllers;

public class SalaryController : Controller
{
    public IActionResult Index()
    { 
        HttpContext.Session.SetInt32("OpenPage", 2);
        ICommand command = new EmployeeCommand<Employee>();
        var userList = command.GetDataList<Employee>();
        return View(new ViewModel.SalaryViewModel{EmployeeList=userList, TypeSalary = TypeSalary.GetTypeSalary(), MonthList = Month.GetMonth(), SystemSalary = SystemSalary.GetSystemSalary()});
    }
    public string AddSalary(Salary salary)
    {
        Console.WriteLine(salary.MonthId);
        ICommand command = new SalaryCommand<Salary>(salary);
        var result=command.Add();
        return result ? "Заплата успешно добавлена" : "Произошла ошибка при добавлении зарплаты";
    }

    public IActionResult GetSalary()
    {
        ICommand command = new SalaryCommand<Salary>();
        var salaryList = command.GetDataList<Salary>();
        command = new EmployeeCommand<Employee>();
        var userList = command.GetDataList<Employee>();
        return View("SalaryList", new SalaryViewModel{ EmployeeList=userList, TypeSalary = TypeSalary.GetTypeSalary(), MonthList = Month.GetMonth(), SystemSalary = SystemSalary.GetSystemSalary(), Salaries = salaryList});
    }
    public IActionResult UpdateSalary(List<Salary> salaries)
    {
        ICommand command = new SalaryCommand<List<Salary>>(salaries);
        command.Update();
        return Redirect("~/Salary");
    }
    public string DeleteSalary(int id)
    {
        ICommand command = new SalaryCommand<int>(id);
        var result= command.Remove();
        return result ? "Зарплата успешно удалена" : "Произошла ошибка при удалении";
    }
}

SalCalc/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    var page = @HttpContextAccessor.HttpContext.Session.GetInt32("OpenPage");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SalCalc</title>
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="js/site.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="nav">
            <div >
                <div>
                    <ul class="ul_nav">
                        <li class="nav-item"><a asp-controller="Home" asp-action="Index"><button class="@((page == 1) ? "button_nav_selected" :"button_nav")">Сотрудники </button></a></li>
                        <li class="nav-item"><a asp-controller="Salary"  asp-action="Index"><button id="but_imp" class="@((page == 2) ? "button_nav_selected" :"button_nav")">Зарплата</button></a></li>
                        <li class="nav-item"><a class="nav-link text-dark"  asp-controller="Report"  asp-action="Index"><button class="@((page == 3) ? "button_nav_selected" :"button_nav")">Отчет</button></a></li>  
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>